EWPP-1644: Open vocabulary association facet translations.
openeuropa/oe_list_pages pull request #115
Opened 2021-10-20 11:32 UTC by upchuk

2021-10-21 18:28 UTC, sergepavle requested changes

2021-10-21 18:28 UTC, sergepavle commented on modules/oe_list_pages_open_vocabularies/src/EventSubscriber/AssociationTranslationSubscriber.php
> +
```suggestion

declare(strict_types = 1);

```

2021-10-21 18:28 UTC, sergepavle commented on modules/oe_list_pages_open_vocabularies/tests/src/Kernel/ListPagesSearchApiConfiguratorTranslationTest.php
> +    /** @var \Drupal\facets\FacetInterface $facet_1 */
```suggestion
    /** @var \Drupal\facets\FacetInterface $facet_one */
```

2021-10-21 18:28 UTC, sergepavle commented on modules/oe_list_pages_open_vocabularies/tests/src/Kernel/ListPagesSearchApiConfiguratorTranslationTest.php
> +    $facet = Facet::load($facet_id_one);
```suggestion
    $facet_one = Facet::load($facet_id_one);
```

2021-10-21 18:28 UTC, sergepavle commented on modules/oe_list_pages_open_vocabularies/tests/src/Kernel/ListPagesSearchApiConfiguratorTranslationTest.php
> +    $this->assertEmpty($config_translation->get());
Did you mean get 'name'?
```suggestion
    $this->assertEmpty($config_translation->get('name'));
```

2021-10-21 18:28 UTC, sergepavle commented on modules/oe_list_pages_open_vocabularies/tests/src/Kernel/ListPagesSearchApiConfiguratorTranslationTest.php
> +    $this->assertEmpty($config_translation->get());
Did you mean get 'name'?
```suggestion
    $this->assertEmpty($config_translation->get());
```

2021-10-25 10:47 UTC, sergepavle submitted a review, later dismissed

2021-11-09 12:52 UTC, sergepavle approved these changes

2021-11-09 12:59 UTC, hernani approved these changes

2021-11-09 13:39 UTC, merged