EWPP-2358: Drupal 9 support.
openeuropa/oe_list_pages pull request #142
Opened 2022-06-20 16:50 UTC by yenyasinn

2022-06-22 12:31 UTC, brummbar requested changes
Please rename commit to "9.4 support". Same for PR.

2022-06-24 14:02 UTC, 22Alexandra submitted a review, later dismissed

2022-06-27 15:15 UTC, nagyad approved these changes

2022-06-30 09:09 UTC, 22Alexandra approved these changes

2022-06-30 09:11 UTC, nagyad approved these changes

2022-06-30 09:14 UTC, brummbar approved these changes

2022-06-30 09:15 UTC, merged