EWPP-2724: Bubble up facet cache.
openeuropa/oe_list_pages pull request #163
Opened 2022-11-16 14:00 UTC by nagyad

2023-01-06 07:45 UTC, upchuk requested changes
I see no tests for any of these changes.

2023-01-06 07:45 UTC, upchuk commented on src/EventSubscriber/QuerySubscriber.php
> +      // Add query tags to the query.
Query tags? Also, if you are gonna put a comment, say why you are adding these tags.

I see in multiple places you are adding the cache tags of the Facet entity to things. What relevant facet cache tags do we need? Do we need to invalidate any caches whenever a facet gets changed (which happens only as a deployment action)? Or are there tags I don't know about?

2023-01-24 11:30 UTC, hernani requested changes
Changes requested

2023-01-24 11:30 UTC, hernani commented on tests/src/Kernel/ListBuilderTest.php
> +    $listBuilder = new ListBuilder($listExecutionManager, $this->entityTypeManager, $pager, $entityRepository, $formBuilder, $facetsUrlGenerator, $processorManager, $requestStack, $urlProcessorManage
$listBuilder = $this->container->get('oe_list_pages.builder'); 

All the remaining services don't need to be instantiated.

2023-01-24 11:30 UTC, hernani commented on tests/src/Kernel/DateStatusTest.php
> +    $this->assertContains($this->facet->getCacheTags()[0], $query->getCacheTags());
Compare this against a static list of cache tags and compare both are similar.

2023-01-24 13:14 UTC, hernani commented on docker-compose.yml
> +      XDEBUG_SESSION: 1
?

2023-01-24 13:20 UTC, hernani approved these changes

2023-01-27 08:40 UTC, upchuk approved these changes

2023-01-27 11:15 UTC, merged