EWPP-3018: Drupal 10 compatibility.
openeuropa/oe_list_pages pull request #181
Opened 2023-05-11 18:05 UTC by brummbar

2023-05-15 16:37 UTC, drishu requested changes
rector reported this modules/oe_list_pages_address/tests/src/Unit/FormatAddressProcessorTest.php:25
-    $country_repository = $this->getMockBuilder(CountryRepositoryInterface::class)
-      ->disableOriginalConstructor()
-      ->getMock();
+    $country_repository = $this->createMock(CountryRepositoryInterface::class);

2023-05-17 07:57 UTC, drishu approved these changes

2023-05-24 09:46 UTC, drishu approved these changes

2023-05-25 08:22 UTC, hernani approved these changes

2023-05-25 08:22 UTC, merged