EWPP-491: List pages configuration subform.
openeuropa/oe_list_pages pull request #42
Opened 2020-11-03 10:41 UTC by upchuk

This PR refactors the list page configuration form to its own independent subform that can also be used elsewhere.

2020-11-05 13:50 UTC, imanoleguskiza requested changes

2020-11-05 13:50 UTC, imanoleguskiza commented on src/Form/ListPageConfigurationSubForm.php
> +      // self::fillDefaultEntityMetaValues().
This is no longer self.

2020-11-09 16:51 UTC, hernani approved these changes

2020-11-09 17:01 UTC, imanoleguskiza approved these changes

2020-11-09 17:02 UTC, merged