EWPP-454: Link to the RSS feed.
openeuropa/oe_list_pages pull request #62
Opened 2021-01-05 15:56 UTC by sergepavle

## OPENEUROPA-454

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-01-06 12:40 UTC, upchuk requested changes

2021-01-06 12:40 UTC, upchuk commented on oe_list_pages.module
> +use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
How come these are added here?

2021-01-06 12:40 UTC, upchuk commented on src/Plugin/ExtraField/Display/ListPageRssLink.php
> + * Extra field displaying the list page pager.
copy paste

2021-01-06 12:40 UTC, upchuk commented on src/ListBuilderInterface.php
> +   * Builds a RSS link.
Builds a link to the RSS representation of the list page.

2021-01-06 12:55 UTC, sergepavle commented on oe_list_pages.module
> +use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
Uncaught leftover.
Removed.

2021-01-07 10:25 UTC, imanoleguskiza approved these changes

2021-01-07 10:26 UTC, upchuk approved these changes

2021-01-12 09:57 UTC, hernani approved these changes

2021-01-12 09:59 UTC, merged