EWPP-671: Add multiselectfilterfieldplugins.
openeuropa/oe_list_pages pull request #67
Opened 2021-01-19 15:56 UTC by imanoleguskiza

## EWPP-671

### Description

Add multiselectfilterfieldplugins

### Change log

- Added: Add multiselectfilterfieldplugins.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-01-21 09:14 UTC, upchuk requested changes

2021-01-21 09:14 UTC, upchuk commented on src/Plugin/MultiselectFilterField/BooleanField.php
> +    $facet = $this->configuration['facet'];
Don't we expect always the facet to be there in all plugins? Throw an exception in the constructor if the facet is missing and then we can rely on it always being there.

2021-01-21 09:59 UTC, imanoleguskiza commented on src/Plugin/facets/widget/ListPagesWidgetBase.php
> -  public function getDefaultValuesLabel(FacetInterface $facet, ListSourceInterface $list_source, ListPresetFilter $filter): string {
Fixed.

2021-01-21 09:59 UTC, imanoleguskiza commented on src/ListPresetFiltersBuilder.php
> +        $filter_value_label = $widget->getDefaultValuesLabel($facet, $filter, $list_source);
Fixed.

2021-01-21 10:04 UTC, imanoleguskiza commented on .gitignore
> +/.gitattributes
This is due to a change in the scaffolding process in the latest drupal versions, the .gitattributes file is placed at the project root so we will need to add it to our .gitignores unless we want to add them to the repo.

2021-01-27 07:43 UTC, upchuk approved these changes

2021-01-27 08:33 UTC, hernani approved these changes

2021-01-27 08:34 UTC, merged