EWPP-719: Selected filters should show up regardless of the results
openeuropa/oe_list_pages pull request #76
Opened 2021-02-08 12:19 UTC by upchuk

2021-02-10 14:58 UTC, hernani submitted a review, later dismissed

2021-02-11 10:12 UTC, imanoleguskiza approved these changes

2021-02-11 12:07 UTC, imanoleguskiza requested changes

2021-02-11 12:07 UTC, imanoleguskiza commented on src/ListBuilder.php
> +    $field_definition = $this->getFacetFieldDefinition($facet, $list_source);
There is a problem here when the indexed field does not map to an actual drupal field (like call_proposals_last_deadline). In this scenario we don't get a definition so we will get an error.

2021-02-14 17:21 UTC, imanoleguskiza submitted a review, later dismissed

2021-02-23 12:48 UTC, hernani approved these changes

2021-02-23 12:51 UTC, imanoleguskiza approved these changes

2021-02-23 12:52 UTC, merged