EWPP-693: Functional test covering open vocabularies fields.
openeuropa/oe_list_pages pull request #77
Opened 2021-02-09 16:33 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-02-19 11:48 UTC, imanoleguskiza requested changes

2021-02-19 11:48 UTC, imanoleguskiza commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    $page->uncheckField('Body');
Is this required?

2021-02-19 11:48 UTC, imanoleguskiza commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +      'title' => 'another yellow fruit',
Why not call this 'a green fruit' since we are tagging it with "green color"? makes it confusing after to read the tests.

2021-02-19 11:48 UTC, imanoleguskiza commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    $this->assertEquals($expected_bundles, $actual_bundles);
This and all the previous assertions are duplicated from other tests that suit them better I think, we could take them out of this particular test class and save some precious precious time.

2021-02-19 12:12 UTC, imanoleguskiza approved these changes

2021-02-22 07:54 UTC, upchuk requested changes

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +  /**
Missing empty line.

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    $installer->installEntityMetaTypeOnContentEntityType('oe_list_page', 'node', [
This is not needed as it gets installed when installing the `oe_list_page_content_type ` module.

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    $association_id = $association->id();
You can just use `$association->id()` where you need the ID.

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    $term_1 = Term::create($values);
Let's be consistent and use `term_one`, `term_two` when writing this and not 1, 2 in variable names.

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +    // Create some test nodes to index and search in.
You said this already :) Maybe split the comments to say that we are making content type one and content type two.

2021-02-22 07:54 UTC, upchuk commented on modules/oe_list_pages_open_vocabularies/tests/src/FunctionalJavascript/OpenVocabulariesFiltersTest.php
> +  public function testListPagePluginFiltersFormConfiguration(): void {
Mmm, this is the only functional test we have of open vocabs. Why aren't we covering having two different associations? That's a critical part of the system the fact that for each association we generate a facet and index field.

2021-02-23 09:50 UTC, imanoleguskiza approved these changes

2021-02-23 11:20 UTC, upchuk approved these changes

2021-02-23 11:20 UTC, merged