EWPP-674: Ensuring filters work also with custom search API fields.
openeuropa/oe_list_pages pull request #82
Opened 2021-02-17 09:18 UTC by upchuk

2021-02-17 13:56 UTC, hernani commented on tests/modules/oe_list_pages_filters_test/src/Plugin/facets/processor/FooFakeFieldProcessor.php
> + * Default status processor for the foo fake field..
..

2021-02-17 13:59 UTC, imanoleguskiza requested changes

2021-02-17 13:59 UTC, imanoleguskiza commented on tests/src/FunctionalJavascript/ListPagesPresetFiltersTest.php
> +    // We should only see Node 1 as the Foo facet defaults to node.
We should only see Node 1 as we configured the Foo facet default value to be 1.

2021-02-18 08:13 UTC, imanoleguskiza approved these changes

2021-02-18 08:49 UTC, merged